// Code generated by mkenv-gen; DO NOT EDIT.
package registry

import (
	_ "github.com/0xa1bed0/mkenv/internal/bricks/langs"
	_ "github.com/0xa1bed0/mkenv/internal/bricks/shells"
	_ "github.com/0xa1bed0/mkenv/internal/bricks/systems"
	_ "github.com/0xa1bed0/mkenv/internal/bricks/tools"
)
const GeneratedRegistryVersion = "v1"

