// Code generated by MockGen. DO NOT EDIT.
// Source: internal/fsops/fsops.go
//
// Generated by this command:
//
//	mockgen -source=internal/fsops/fsops.go -destination=internal/fsops/mocks/fsops.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	fs "io/fs"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPathOps is a mock of PathOps interface.
type MockPathOps struct {
	ctrl     *gomock.Controller
	recorder *MockPathOpsMockRecorder
	isgomock struct{}
}

// MockPathOpsMockRecorder is the mock recorder for MockPathOps.
type MockPathOpsMockRecorder struct {
	mock *MockPathOps
}

// NewMockPathOps creates a new mock instance.
func NewMockPathOps(ctrl *gomock.Controller) *MockPathOps {
	mock := &MockPathOps{ctrl: ctrl}
	mock.recorder = &MockPathOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPathOps) EXPECT() *MockPathOpsMockRecorder {
	return m.recorder
}

// Abs mocks base method.
func (m *MockPathOps) Abs(path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Abs", path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Abs indicates an expected call of Abs.
func (mr *MockPathOpsMockRecorder) Abs(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Abs", reflect.TypeOf((*MockPathOps)(nil).Abs), path)
}

// Clean mocks base method.
func (m *MockPathOps) Clean(path string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clean", path)
	ret0, _ := ret[0].(string)
	return ret0
}

// Clean indicates an expected call of Clean.
func (mr *MockPathOpsMockRecorder) Clean(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clean", reflect.TypeOf((*MockPathOps)(nil).Clean), path)
}

// IsAbs mocks base method.
func (m *MockPathOps) IsAbs(path string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAbs", path)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAbs indicates an expected call of IsAbs.
func (mr *MockPathOpsMockRecorder) IsAbs(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAbs", reflect.TypeOf((*MockPathOps)(nil).IsAbs), path)
}

// Join mocks base method.
func (m *MockPathOps) Join(elem ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range elem {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Join", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// Join indicates an expected call of Join.
func (mr *MockPathOpsMockRecorder) Join(elem ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockPathOps)(nil).Join), elem...)
}

// Rel mocks base method.
func (m *MockPathOps) Rel(basepath, targpath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rel", basepath, targpath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rel indicates an expected call of Rel.
func (mr *MockPathOpsMockRecorder) Rel(basepath, targpath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rel", reflect.TypeOf((*MockPathOps)(nil).Rel), basepath, targpath)
}

// MockOSOps is a mock of OSOps interface.
type MockOSOps struct {
	ctrl     *gomock.Controller
	recorder *MockOSOpsMockRecorder
	isgomock struct{}
}

// MockOSOpsMockRecorder is the mock recorder for MockOSOps.
type MockOSOpsMockRecorder struct {
	mock *MockOSOps
}

// NewMockOSOps creates a new mock instance.
func NewMockOSOps(ctrl *gomock.Controller) *MockOSOps {
	mock := &MockOSOps{ctrl: ctrl}
	mock.recorder = &MockOSOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOSOps) EXPECT() *MockOSOpsMockRecorder {
	return m.recorder
}

// Stat mocks base method.
func (m *MockOSOps) Stat(name string) (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", name)
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockOSOpsMockRecorder) Stat(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockOSOps)(nil).Stat), name)
}

// MockDirWalker is a mock of DirWalker interface.
type MockDirWalker struct {
	ctrl     *gomock.Controller
	recorder *MockDirWalkerMockRecorder
	isgomock struct{}
}

// MockDirWalkerMockRecorder is the mock recorder for MockDirWalker.
type MockDirWalkerMockRecorder struct {
	mock *MockDirWalker
}

// NewMockDirWalker creates a new mock instance.
func NewMockDirWalker(ctrl *gomock.Controller) *MockDirWalker {
	mock := &MockDirWalker{ctrl: ctrl}
	mock.recorder = &MockDirWalkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDirWalker) EXPECT() *MockDirWalkerMockRecorder {
	return m.recorder
}

// WalkDir mocks base method.
func (m *MockDirWalker) WalkDir(root string, fn fs.WalkDirFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WalkDir", root, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WalkDir indicates an expected call of WalkDir.
func (mr *MockDirWalkerMockRecorder) WalkDir(root, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WalkDir", reflect.TypeOf((*MockDirWalker)(nil).WalkDir), root, fn)
}
