package main

import (
	"bufio"
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	fmt.Println("Generating bricks registry...")
	mod, err := modulePath("go.mod")
	if err != nil {
		panic(err)
	}

	var imports []string
	err = filepath.WalkDir("internal/bricks", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			return nil
		}

		// allow local opt-out
		if _, err := os.Stat(filepath.Join(path, ".mkenv.skip")); err == nil {
			return filepath.SkipDir
		}

		ents, _ := os.ReadDir(path)
		hasGo := false
		for _, e := range ents {
			if e.IsDir() {
				continue
			}
			n := e.Name()
			if strings.HasSuffix(n, ".go") && !strings.HasSuffix(n, "_test.go") {
				hasGo = true
				break
			}
		}
		if hasGo {
			imports = append(imports, mod+"/"+filepath.ToSlash(path))
		}
		return nil
	})

	if err != nil {
		panic(err)
	}

	sort.Strings(imports)
	imports = dedupe(imports)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by mkenv-gen; DO NOT EDIT.\n")
	buf.WriteString("package registry\n\n")
	buf.WriteString("import (\n")
	for _, imp := range imports {
		fmt.Fprintf(&buf, "\t_ %q\n", imp)
	}
	buf.WriteString(")\n\n")
	buf.WriteString("const GeneratedRegistryVersion = \"v1\"\n\n")

	if err := os.MkdirAll("internal/registry", 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile("internal/registry/zz_generated_imports.go", buf.Bytes(), 0o644); err != nil {
		panic(err)
	}
}

func modulePath(goMod string) (string, error) {
	f, err := os.Open(goMod)
	if err != nil {
		return "", err
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module ")), nil
		}
	}
	return "", fmt.Errorf("module path not found in %s", goMod)
}

func dedupe(xs []string) []string {
	if len(xs) == 0 {
		return xs
	}
	out := []string{xs[0]}
	for i := 1; i < len(xs); i++ {
		if xs[i] != xs[i-1] {
			out = append(out, xs[i])
		}
	}
	return out
}
